import { buildStage3CompraAgil, buildStage4, buildStage5 } from './stage-builders.js';

export const stages = [
  {
    id: 1,
    name: 'SOLPED',
    status: 'Finalizada',
    summary: '6 sub-pasos · 5 ejecutados · 1 omitido',
    expanded: true,
    state: 'done',
    totalTime: 'Total etapa: 2 d 6 h (24-06 → 26-06)',
    steps: [
      {
        id: '1.1',
        name: 'Creación de solicitud',
        responsible: { unit: 'Unidad Solicitante', role: 'Solicitante', name: 'Juan Astorga' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver formulario' },
        secondaryLine: 'Tiempo transcurrido: 0 d 3 h · Última modificación: 24-06-2026 · Modalidad indicada: Compra Ágil · Monto estimado: $ 1.250.000 (≤ 100 UTM)',
      },
      {
        id: '1.2',
        name: 'Visto bueno de jefatura',
        responsible: { unit: 'Unidad Solicitante', role: 'Aprobador de unidad', name: 'María Rojas' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver aprobación' },
        secondaryLine: 'Tiempo transcurrido: 1 d 2 h · Última modificación: 25-06-2026',
      },
      {
        id: '1.3',
        name: 'Verificación de disponibilidad presupuestaria',
        responsible: { unit: 'DAF Finanzas', role: 'Formulador DAF / verificación', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver verificación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 5 h · Última modificación: 25-06-2026',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.4',
        name: 'Solicitar financiamiento a DAF',
        responsible: { unit: 'Unidad Solicitante', role: 'Solicitante', name: '—' },
        status: 'omitted',
        action: { type: 'badge', label: 'Omitido (optativo)' },
        secondaryLine: 'No requerido: disponibilidad verificada en 1.3',
        omitted: true,
        origin: { kind: 'module', label: 'Presupuestos', mode: 'observado' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.5',
        name: 'Emisión de CDP firmado',
        responsible: { unit: 'DAF Finanzas', role: 'Firmante CDP', name: 'Pedro Soto' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver CDP' },
        secondaryLine: 'Tiempo transcurrido: 1 d 0 h · Última modificación: 26-06-2026 · Firma electrónica (FirmaGob)',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.6',
        name: 'Generación de preobligación',
        responsible: { unit: 'DAF Finanzas', role: 'Firmante CDP', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver preobligación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 1 h · Monto preobligado: $ 1.250.000 · También: Contabilidad',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia', also: ['Contabilidad'] },
        borderModules: ['Presupuestos', 'Contabilidad'],
      },
    ],
  },
  {
    id: 2,
    name: 'Modalidad de Compra',
    status: 'Finalizada',
    summary: 'Compra Ágil ratificada · Vinculada a MP · ID Cotización: 4021-33-COT26',
    expanded: true,
    state: 'done',
    totalTime: 'Total etapa: 0 d 5 h (26-06 → 27-06)',
    steps: [
      {
        id: '2.1',
        name: 'Ratificación o selección de modalidad',
        responsible: { unit: 'DAF Finanzas', role: 'Gestor de compra', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver decisión' },
        secondaryLine: 'Tiempo transcurrido: 0 d 2 h · Compra Ágil ratificada (gateway V1–V8 OK) · Aprobación de jefatura solicitada',
      },
      {
        id: '2.2',
        name: 'Aprobación de modalidad por jefatura',
        responsible: { unit: 'DAF Finanzas', role: 'Aprobador de modalidad', name: 'Marcela Iturra' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver aprobación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 1 h · Aprobada sin observaciones — sub-paso condicional (P-38)',
      },
      {
        id: '2.3',
        name: 'Vinculación del proceso en Mercado Público',
        responsible: { unit: 'DAF Abastecimiento', role: 'Gestor de compra', name: 'Rodrigo Muñoz' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver vínculo MP' },
        secondaryLine: 'Tiempo transcurrido: 0 d 2 h · ID Cotización: 4021-33-COT26 · Vinculación inmediata (CA)',
        origin: { kind: 'external', label: 'Mercado Público', mode: 'solo lectura' },
      },
    ],
  },
  buildStage3CompraAgil(),
  buildStage4({
    profileLabel: 'Bien físico, entrega única — insumos de oficina',
    ocNumber: '4021-33-SE26',
    provider: 'Comercial Sur SpA',
    allDone: false,
  }),
  buildStage5({
    allDone: false,
    ocNumber: '4021-33-SE26',
    provider: 'Comercial Sur SpA',
  }),
];
