import { stage3Stub, buildStage4, buildStage5 } from './stage-builders.js';

export const stages = [
  {
    id: 1,
    name: 'SOLPED',
    status: 'Finalizada',
    summary: '6 sub-pasos · 5 ejecutados · 1 omitido',
    expanded: true,
    state: 'done',
    totalTime: 'Total etapa: 4 d 1 h (15-01 → 19-01)',
    steps: [
      {
        id: '1.1',
        name: 'Creación de solicitud',
        responsible: { unit: 'Dirección de Obras', role: 'Usuario', name: 'Felipe Rojas' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver formulario' },
        secondaryLine: 'Tiempo transcurrido: 0 d 5 h · Modalidad indicada: Licitación Pública · Monto estimado: $ 185.000.000 (> 100 UTM)',
      },
      {
        id: '1.2',
        name: 'Visto bueno de jefatura',
        responsible: { unit: 'Dirección de Obras', role: 'Aprobador', name: 'Claudia Muñoz' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver aprobación' },
        secondaryLine: 'Tiempo transcurrido: 1 d 3 h · Última modificación: 16-01-2026',
      },
      {
        id: '1.3',
        name: 'Verificación de disponibilidad presupuestaria',
        responsible: { unit: 'DAF Finanzas', role: 'Usuario', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver verificación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 8 h · Partida 22.04.01.002',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.4',
        name: 'Solicitar financiamiento a DAF',
        responsible: { unit: 'Dirección de Obras', role: 'Usuario', name: '—' },
        status: 'omitted',
        action: { type: 'badge', label: 'Omitido (optativo)' },
        secondaryLine: 'No requerido: disponibilidad verificada en 1.3',
        omitted: true,
        origin: { kind: 'module', label: 'Presupuestos', mode: 'observado' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.5',
        name: 'Emisión de CDP firmado',
        responsible: { unit: 'DAF Finanzas', role: 'Aprobador', name: 'Pedro Soto' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver CDP' },
        secondaryLine: 'Tiempo transcurrido: 1 d 4 h · CDP N° 2026-0089',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.6',
        name: 'Generación de preobligación',
        responsible: { unit: 'DAF Finanzas', role: 'Usuario', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver preobligación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 3 h · Monto preobligado: $ 185.000.000 (estimado — ajuste al adjudicar)',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia', also: ['Contabilidad'] },
        borderModules: ['Presupuestos', 'Contabilidad'],
      },
    ],
  },
  {
    id: 2,
    name: 'Modalidad de Compra',
    status: 'Finalizada',
    summary: 'Licitación Pública confirmada · V7 tramo informado · 2.3 diferido a etapa 3',
    expanded: true,
    state: 'done',
    totalTime: 'Total etapa: 0 d 6 h (19-01)',
    steps: [
      {
        id: '2.1',
        name: 'Ratificación o selección de modalidad',
        responsible: { unit: 'DAF Finanzas', role: 'Usuario', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver decisión' },
        secondaryLine: 'Tiempo transcurrido: 0 d 4 h · LP confirmada · V7: tramo medio, plazo mín. 20 días · V8: garantías seriedad y fiel cumplimiento informadas',
      },
      {
        id: '2.2',
        name: 'Aprobación de modalidad por jefatura',
        responsible: { unit: 'DAF Finanzas', role: 'Aprobador', name: 'Marcela Iturra' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver aprobación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 2 h · Aprobada — monto alto',
      },
      {
        id: '2.3',
        name: 'Vinculación del proceso en Mercado Público',
        responsible: { unit: 'DAF Abastecimiento', role: 'Usuario', name: '—' },
        status: 'omitted',
        action: { type: 'badge', label: 'Omitido (optativo)' },
        secondaryLine: 'Diferido al sub-paso 3.5 de Licitación Pública (tras bases aprobadas y Toma de Razón si aplicó)',
        omitted: true,
        origin: { kind: 'external', label: 'Mercado Público', mode: 'solo lectura' },
      },
    ],
  },
  stage3Stub('Licitación Pública', 'sgm-docs/modulos/adquisiciones/3. licitacion-publica/3-resolucion-compra.md'),
  buildStage4({
    profileLabel: 'Servicio de mantención de flota — hitos de ejecución',
    ocNumber: '4021-12-LP26-OC',
    provider: 'Taller Municipal SpA',
    omitInventory: true,
    serviceProfile: true,
    allDone: true,
  }),
  buildStage5({
    allDone: true,
    ocNumber: '4021-12-LP26-OC',
    provider: 'Taller Municipal SpA',
  }),
];
