import { stage3Stub, buildStage4, buildStage5 } from './stage-builders.js';

export const stages = [
  {
    id: 1,
    name: 'SOLPED',
    status: 'Finalizada',
    summary: '6 sub-pasos · 5 ejecutados · 1 omitido',
    expanded: true,
    state: 'done',
    totalTime: 'Total etapa: 1 d 8 h (05-05 → 06-05)',
    steps: [
      {
        id: '1.1',
        name: 'Creación de solicitud',
        responsible: { unit: 'DAF Abastecimiento', role: 'Usuario', name: 'Rodrigo Muñoz' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver formulario' },
        secondaryLine: 'Tiempo transcurrido: 0 d 2 h · Modalidad: Trato Directo · Causal art. 8 letra c) · Resolución Fundada adjunta · Monto: $ 2.400.000',
      },
      {
        id: '1.2',
        name: 'Visto bueno de jefatura',
        responsible: { unit: 'DAF Abastecimiento', role: 'Aprobador', name: 'Marcela Iturra' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver aprobación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 4 h · Urgencia operacional validada',
      },
      {
        id: '1.3',
        name: 'Verificación de disponibilidad presupuestaria',
        responsible: { unit: 'DAF Finanzas', role: 'Usuario', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver verificación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 3 h',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.4',
        name: 'Solicitar financiamiento a DAF',
        responsible: { unit: 'DAF Abastecimiento', role: 'Usuario', name: '—' },
        status: 'omitted',
        action: { type: 'badge', label: 'Omitido (optativo)' },
        secondaryLine: 'No requerido: disponibilidad verificada en 1.3',
        omitted: true,
        origin: { kind: 'module', label: 'Presupuestos', mode: 'observado' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.5',
        name: 'Emisión de CDP firmado',
        responsible: { unit: 'DAF Finanzas', role: 'Aprobador', name: 'Pedro Soto' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver CDP' },
        secondaryLine: 'Tiempo transcurrido: 0 d 5 h · CDP N° 2026-1204',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.6',
        name: 'Generación de preobligación',
        responsible: { unit: 'DAF Finanzas', role: 'Usuario', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver preobligación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 2 h · Monto preobligado: $ 2.400.000',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia', also: ['Contabilidad'] },
        borderModules: ['Presupuestos', 'Contabilidad'],
      },
    ],
  },
  {
    id: 2,
    name: 'Modalidad de Compra',
    status: 'Finalizada',
    summary: 'Trato Directo confirmado · Jefatura aprobó · 2.3 diferido a publicación',
    expanded: true,
    state: 'done',
    totalTime: 'Total etapa: 0 d 8 h (06-05)',
    steps: [
      {
        id: '2.1',
        name: 'Ratificación o selección de modalidad',
        responsible: { unit: 'DAF Finanzas', role: 'Usuario', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver decisión' },
        secondaryLine: 'Tiempo transcurrido: 0 d 3 h · Trato Directo confirmado (V3 causal OK) · `requires_jefatura_approval = true`',
      },
      {
        id: '2.2',
        name: 'Aprobación de modalidad por jefatura',
        responsible: { unit: 'DAF Finanzas', role: 'Aprobador', name: 'Marcela Iturra' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver aprobación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 2 h · Aprobada — modalidad sensible (TD)',
      },
      {
        id: '2.3',
        name: 'Vinculación del proceso en Mercado Público',
        responsible: { unit: 'DAF Abastecimiento', role: 'Usuario', name: '—' },
        status: 'omitted',
        action: { type: 'badge', label: 'Omitido (optativo)' },
        secondaryLine: 'Diferido al subproceso de Trato Directo — momento de publicación (regla 24 h)',
        omitted: true,
        origin: { kind: 'external', label: 'Mercado Público', mode: 'solo lectura' },
      },
    ],
  },
  stage3Stub('Trato Directo', 'sgm-docs/modulos/adquisiciones/4. trato-directo/3-resolucion-compra.md'),
  buildStage4({
    profileLabel: 'Repuestos críticos — bien físico, entrega urgente',
    ocNumber: '4021-05-TD26-OC',
    provider: 'Repuestos Industriales SpA',
    allDone: false,
  }),
  buildStage5({
    allDone: false,
    ocNumber: '4021-05-TD26-OC',
    provider: 'Repuestos Industriales SpA',
  }),
];
