export const expediente = {
  id: 'ADQ-2026-00123',
  glosa: '[Nombre / glosa de la compra]',
  modality: 'Compra Ágil',
  unit: '[Unidad Solicitante]',
  globalStatus: 'En curso — etapa 3 de 5',
};

export const stages = [
  {
    id: 1,
    name: 'SOLPED',
    status: 'Finalizada',
    summary: '6 sub-pasos · 5 ejecutados · 1 omitido',
    expanded: true,
    state: 'done',
    totalTime: 'Total etapa: 2 d 6 h (24-06 → 26-06)',
    steps: [
      {
        id: '1.1',
        name: 'Creación de solicitud',
        responsible: { unit: 'Unidad Solicitante', role: 'Usuario', name: 'Juan Astorga' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver formulario' },
        secondaryLine: 'Tiempo transcurrido: 0 d 3 h · Última modificación: 24-06-2026',
      },
      {
        id: '1.2',
        name: 'Visto bueno de jefatura',
        responsible: { unit: 'Unidad Solicitante', role: 'Aprobador', name: 'María Rojas' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver aprobación' },
        secondaryLine: 'Tiempo transcurrido: 1 d 2 h · Última modificación: 25-06-2026',
      },
      {
        id: '1.3',
        name: 'Verificación de disponibilidad presupuestaria',
        responsible: { unit: 'DAF Finanzas', role: 'Usuario', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver verificación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 5 h · Última modificación: 25-06-2026',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.4',
        name: 'Solicitar financiamiento a DAF',
        responsible: { unit: 'Unidad Solicitante', role: 'Usuario', name: '—' },
        status: 'omitted',
        action: { type: 'secondary', label: 'Ver solicitud' },
        secondaryLine: 'No requerido: disponibilidad verificada en 1.3',
        omitted: true,
        origin: { kind: 'module', label: 'Presupuestos', mode: 'observado' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.5',
        name: 'Emisión de CDP firmado',
        responsible: { unit: 'DAF Finanzas', role: 'Aprobador', name: 'Pedro Soto' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver CDP' },
        secondaryLine: 'Tiempo transcurrido: 1 d 0 h · Última modificación: 26-06-2026 · Firma electrónica (FirmaGob) · Revalidación Presupuestos al emitir',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia' },
        borderModules: ['Presupuestos'],
      },
      {
        id: '1.6',
        name: 'Generación de preobligación',
        responsible: { unit: 'DAF Finanzas', role: 'Usuario', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver preobligación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 1 h · Última modificación: 26-06-2026 · Monto preobligado: $[monto] · También: Contabilidad',
        origin: { kind: 'module', label: 'Presupuestos', mode: 'dependencia', also: ['Contabilidad'] },
        borderModules: ['Presupuestos', 'Contabilidad'],
      },
    ],
  },
  {
    id: 2,
    name: 'Modalidad de Compra',
    status: 'Finalizada',
    summary: 'Compra Ágil ratificada (gateway OK) · Aprobada por jefatura · Vinculada a MP · ID Cotización: 4021-33-COT26 · Total etapa: 0 d 5 h',
    expanded: true,
    state: 'done',
    totalTime: 'Total etapa: 0 d 5 h (26-06 → 27-06)',
    steps: [
      {
        id: '2.1',
        name: 'Ratificación o selección de modalidad',
        responsible: { unit: 'DAF Finanzas', role: 'Usuario', name: 'Carla Fuentes' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver decisión' },
        secondaryLine: 'Tiempo transcurrido: 0 d 2 h · 26-06-2026 · Compra Ágil ratificada (gateway V1–V8 OK) · Aprobación de jefatura solicitada (`requires_jefatura_approval = true`) · CaseStep de etapa 3 instanciados',
      },
      {
        id: '2.2',
        name: 'Aprobación de modalidad por jefatura',
        responsible: { unit: 'DAF Finanzas', role: 'Aprobador', name: 'Marcela Iturra' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver aprobación' },
        secondaryLine: 'Tiempo transcurrido: 0 d 1 h · 26-06-2026 · Solicitada en 2.1 · Aprobada sin observaciones — sub-paso condicional, pendiente de ratificación DM (P-38)',
      },
      {
        id: '2.3',
        name: 'Vinculación del proceso en Mercado Público',
        responsible: { unit: 'DAF Abastecimiento', role: 'Usuario', name: 'Rodrigo Muñoz' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver vínculo MP' },
        secondaryLine: 'Tiempo transcurrido: 0 d 2 h · 27-06-2026 · ID Cotización: 4021-33-COT26 · SOLPED bloqueada «En proceso de cotización»',
        origin: { kind: 'external', label: 'Mercado Público', mode: 'solo lectura' },
      },
    ],
  },
  {
    id: 3,
    name: 'Resolución de Compra',
    status: 'En curso',
    expanded: true,
    state: 'active',
    note: 'Caminos alternativos 3.5 (rechazo de OC) y 3.6 (proceso desierto): no se listan como pendientes — aparecen en el timeline solo si ocurren.',
    steps: [
      {
        id: '3.1',
        name: 'Período de cotización',
        responsible: { unit: 'Mercado Público', role: '—', name: '(proceso externo)' },
        status: 'done',
        action: { type: 'badge', label: 'Finalizado' },
        secondaryLine: 'Tiempo transcurrido: 3 d 0 h · Cierre: 30-06-2026 · 4 cotizaciones recibidas (1ª ronda MiPyme)',
        origin: { kind: 'external', label: 'Mercado Público', mode: 'solo lectura' },
      },
      {
        id: '3.2',
        name: 'Cierre y selección de oferta',
        responsible: { unit: 'DAF Abastecimiento', role: 'Usuario', name: 'Rodrigo Muñoz' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver selección' },
        secondaryLine: 'Tiempo transcurrido: 0 d 6 h · 01-07-2026 · Registro manual (modo degradado) — MP prevalece si difiere',
        origin: { kind: 'external', label: 'Mercado Público', mode: 'solo lectura' },
      },
      {
        id: '3.3',
        name: 'Emisión de la OC',
        responsible: { unit: 'DAF Abastecimiento', role: 'Usuario', name: 'Rodrigo Muñoz' },
        status: 'done',
        action: { type: 'secondary', label: 'Ver OC' },
        secondaryLine: 'Tiempo transcurrido: 0 d 2 h · 02-07-2026 · OC N° 4021-33-SE26 · Habilidad revalidada',
        origin: { kind: 'external', label: 'Mercado Público', mode: 'solo lectura' },
      },
      {
        id: '3.4',
        name: 'Aceptación de la OC',
        responsible: { unit: 'Proveedor (MP)', role: 'Externo', name: 'Comercial Sur SpA' },
        status: 'in_progress',
        current: true,
        action: { type: 'badge', label: 'En curso' },
        secondaryLine: 'Tiempo transcurrido: 5 d 1 h (desde emisión de OC)',
        pendingCondition: 'Condición pendiente: lectura MP «OC Aceptada» (confirmada) → gatilla Compromiso Cierto por monto real',
        origin: { kind: 'external', label: 'Mercado Público', mode: 'solo lectura' },
      },
    ],
  },
  {
    id: 4,
    name: 'Recepción Conforme',
    status: 'Pendiente',
    summary: 'Responsable previsto: Bodega / Unidad Solicitante · Perfil: bien físico, entrega única',
    expanded: true,
    state: 'pending',
    note: 'Perfil de recepción: bien físico, entrega única. Camino 4.5 (no conforme) no se lista como pendiente — aparece solo si hay rechazo.',
    steps: [
      {
        id: '4.1',
        name: 'Registro de la recepción',
        responsible: { unit: 'Bodega', role: 'Usuario', name: 'Ana Pérez' },
        status: 'pending',
        action: { type: 'primary', label: 'Registrar recepción' },
        secondaryLine: 'Pendiente de entrega del proveedor · Contra líneas de OC N° 4021-33-SE26',
      },
      {
        id: '4.2',
        name: 'Verificación de conformidad',
        responsible: { unit: 'Unidad Solicitante', role: 'Aprobador', name: 'Juan Astorga' },
        status: 'pending',
        action: { type: 'badge', label: 'Pendiente' },
        secondaryLine: 'Requiere recepción registrada (4.1) · Doble conformidad: unidad requirente valida entrega de Bodega',
      },
      {
        id: '4.3',
        name: 'Alta en inventario / activo fijo',
        responsible: { unit: 'Bodega', role: 'Usuario', name: 'Ana Pérez' },
        status: 'pending',
        action: { type: 'badge', label: 'Pendiente' },
        secondaryLine: 'Condicional (optativo): solo bienes físicos aceptados · Proveedor de inventario por configurar',
      },
      {
        id: '4.4',
        name: 'Devengado',
        responsible: { unit: 'Contabilidad', role: 'N/A', name: '(automático)' },
        status: 'pending',
        action: { type: 'badge', label: 'Pendiente' },
        secondaryLine: 'Gatillado por conformidad (4.2) · Contra compromiso de 3.4 · Arranca reloj legal de pago (30 días)',
        origin: { kind: 'module', label: 'Contabilidad', mode: 'dependencia' },
        borderModules: ['Contabilidad'],
      },
    ],
  },
  {
    id: 5,
    name: 'Pago',
    status: 'Pendiente',
    summary: 'Etapa observada · Tesorería · El reloj legal de pago (30 días) se mostrará aquí al recibirse la factura',
    expanded: true,
    state: 'pending',
    note: 'Etapa observada — los sub-pasos reflejan eventos de Contabilidad y Tesorería; el reloj legal de pago (30 días) se activa al recibirse la factura.',
    steps: [
      {
        id: '5.1',
        name: 'Cruce de 3 vías (Match)',
        responsible: { unit: 'Contabilidad', role: 'N/A', name: '(automático)' },
        status: 'pending',
        action: { type: 'badge', label: 'Pendiente' },
        secondaryLine: 'Requiere OC (MP) + recepción conforme (SGM) + factura (SII) · También: Contabilidad',
        origin: { kind: 'external', label: 'Mercado Público', mode: 'solo lectura' },
      },
      {
        id: '5.2',
        name: 'Registro de Devengado',
        responsible: { unit: 'Contabilidad', role: 'Aprobador', name: '—' },
        status: 'pending',
        action: { type: 'badge', label: 'Pendiente' },
        secondaryLine: 'Requiere match validado (5.1)',
        origin: { kind: 'module', label: 'Contabilidad', mode: 'dependencia' },
        borderModules: ['Contabilidad'],
      },
      {
        id: '5.3',
        name: 'Generación de Decreto de Pago',
        responsible: { unit: 'Contabilidad', role: 'Aprobador', name: '—' },
        status: 'pending',
        action: { type: 'badge', label: 'Pendiente' },
        secondaryLine: 'Requiere devengado registrado (5.2) · Firma vía FirmaGob al emitir',
      },
      {
        id: '5.4',
        name: 'Ejecución del pago',
        responsible: { unit: 'Tesorería', role: 'Aprobador', name: '—' },
        status: 'pending',
        action: { type: 'badge', label: 'Pendiente' },
        secondaryLine: 'Plazo legal: 30 días corridos desde factura',
        origin: { kind: 'module', label: 'Tesorería', mode: 'observado' },
        borderModules: ['Tesorería'],
      },
    ],
  },
];
