/** Presets de formularios transversales por expediente demo. */
export const formPresets = {
  'ADQ-2026-00123': {
    solpedNumber: '1234',
    solped: {
      unit: 'Unidad Solicitante',
      description: 'Adquisición de insumos de oficina',
      justification: 'Reposición de stock según plan anual.',
      date: '2026-06-24',
      purchaseModality: 'agile_purchase',
      showResolution: false,
      lineDescription: 'Resma papel carta',
      lineQty: '50',
      linePrice: '4500',
      estimatedAmount: '1250000',
    },
    modalidad: {
      unit: 'Unidad Solicitante',
      modalityLabel: 'Compra Ágil (provisional)',
      monto: '1250000',
      modality: 'agile_purchase',
      catalogCm: false,
      jefaturaApproval: true,
    },
    vinculacionMp: {
      modalityLabel: 'Compra Ágil',
      mpCode: '4021-33-COT26',
      mpCodeLabel: 'ID Cotización',
      deepLinkLabel: 'Gestionar cotización en MP',
      statusLine: 'Tipo esperado: Cotización · Vinculación inmediata (CA)',
    },
    recepcion: {
      ocHeader: 'OC 4021-33-SE26 — Recepción conforme',
      ocInfo: '4021-33-SE26 · Proveedor: Comercial Sur SpA · Monto: $ 1.250.000',
      receiver: 'Ana Pérez (usuario actual)',
      lineItem: 'Resma papel carta',
      ocQty: '50',
    },
    pago: {
      ocHeader: 'OC 4021-33-SE26 — Cruce de 3 vías',
      ocAmount: '$ 1.250.000',
      ocSyncDate: '02/07/2026',
      recepcionInfo: 'Estado: Conforme · Fecha: 15/07/2026',
      invoiceAmount: '$ 1.250.000',
    },
  },
  'ADQ-2026-00089': {
    solpedNumber: '8891',
    solped: {
      unit: 'DAF Administración',
      description: 'Mobiliario ergonómico para oficinas municipales',
      justification: 'Renovación de puestos de trabajo según diagnóstico ergonómico 2026.',
      date: '2026-03-10',
      purchaseModality: 'framework_agreement',
      showResolution: false,
      lineDescription: 'Silla ergonómica CM-8842',
      lineQty: '24',
      linePrice: '200000',
      estimatedAmount: '4800000',
    },
    modalidad: {
      unit: 'DAF Administración',
      modalityLabel: 'Convenio Marco (provisional)',
      monto: '4800000',
      modality: 'framework_agreement',
      catalogCm: true,
      jefaturaApproval: true,
    },
    vinculacionMp: {
      modalityLabel: 'Convenio Marco',
      mpCode: '4021-88-IC26',
      mpCodeLabel: 'ID Intención de Compra',
      deepLinkLabel: 'Gestionar Gran Compra en MP',
      statusLine: 'Tipo esperado: Intención de Compra · Vinculación inmediata (CM)',
    },
    recepcion: {
      ocHeader: 'OC 4021-88-OC26 — Recepción conforme',
      ocInfo: '4021-88-OC26 · Proveedor: Mobiliario Chile Ltda. · Monto: $ 4.800.000',
      receiver: 'Sofía Núñez (usuario actual)',
      lineItem: 'Silla ergonómica CM-8842',
      ocQty: '24',
    },
    pago: {
      ocHeader: 'OC 4021-88-OC26 — Cruce de 3 vías',
      ocAmount: '$ 4.800.000',
      ocSyncDate: '28/03/2026',
      recepcionInfo: 'Estado: Conforme · Fecha: 05/04/2026',
      invoiceAmount: '$ 4.800.000',
    },
  },
  'ADQ-2026-00045': {
    solpedNumber: '4512',
    solped: {
      unit: 'Dirección de Obras',
      description: 'Servicio de mantención de flota municipal',
      justification: 'Contrato anual de mantención preventiva y correctiva de vehículos municipales.',
      date: '2026-01-15',
      purchaseModality: 'public_tender',
      showResolution: false,
      lineDescription: 'Mantención flota (12 meses)',
      lineQty: '1',
      linePrice: '185000000',
      estimatedAmount: '185000000',
    },
    modalidad: {
      unit: 'Dirección de Obras',
      modalityLabel: 'Licitación Pública (provisional)',
      monto: '185000000',
      modality: 'public_tender',
      catalogCm: false,
      jefaturaApproval: true,
    },
    vinculacionMp: {
      modalityLabel: 'Licitación Pública',
      mpCode: '',
      mpCodeLabel: 'ID Licitación',
      deepLinkLabel: 'Gestionar licitación en MP',
      statusLine: 'Vinculación diferida al sub-paso 3.5 (tras bases aprobadas)',
    },
    recepcion: {
      ocHeader: 'OC 4021-12-LP26-OC — Recepción conforme',
      ocInfo: '4021-12-LP26-OC · Proveedor: Taller Municipal SpA · Monto: $ 178.500.000 (adjudicado)',
      receiver: 'Felipe Rojas (usuario actual)',
      lineItem: 'Mantención flota — hito mensual',
      ocQty: '1',
    },
    pago: {
      ocHeader: 'OC 4021-12-LP26-OC — Cruce de 3 vías',
      ocAmount: '$ 178.500.000',
      ocSyncDate: '15/06/2026',
      recepcionInfo: 'Estado: Conforme · Fecha: 20/06/2026 · Servicio',
      invoiceAmount: '$ 178.500.000',
    },
  },
  'ADQ-2026-00012': {
    solpedNumber: '1205',
    solped: {
      unit: 'DAF Abastecimiento',
      description: 'Repuestos críticos para maquinaria municipal',
      justification: 'Urgencia operacional: falla de equipo impide prestación del servicio de aseo.',
      date: '2026-05-05',
      purchaseModality: 'direct_procurement',
      showResolution: true,
      lineDescription: 'Kit reparación hidráulica',
      lineQty: '2',
      linePrice: '1200000',
      estimatedAmount: '2400000',
    },
    modalidad: {
      unit: 'DAF Abastecimiento',
      modalityLabel: 'Trato Directo (provisional)',
      monto: '2400000',
      modality: 'direct_procurement',
      catalogCm: false,
      jefaturaApproval: true,
      tdCause: 'Art. 8 letra c) Ley 19.886 — urgencia impostergable por falla de equipo crítico.',
    },
    vinculacionMp: {
      modalityLabel: 'Trato Directo',
      mpCode: '',
      mpCodeLabel: 'ID proceso publicado',
      deepLinkLabel: 'Registrar publicación en MP',
      statusLine: 'Vinculación diferida al momento de publicación (regla 24 h)',
    },
    recepcion: {
      ocHeader: 'OC 4021-05-TD26-OC — Recepción conforme',
      ocInfo: '4021-05-TD26-OC · Proveedor: Repuestos Industriales SpA · Monto: $ 2.400.000',
      receiver: 'Rodrigo Muñoz (usuario actual)',
      lineItem: 'Kit reparación hidráulica',
      ocQty: '2',
    },
    pago: {
      ocHeader: 'OC 4021-05-TD26-OC — Cruce de 3 vías',
      ocAmount: '$ 2.400.000',
      ocSyncDate: '12/05/2026',
      recepcionInfo: 'Estado: Conforme · Fecha: 18/05/2026',
      invoiceAmount: '$ 2.400.000',
    },
  },
  'ADQ-2026-00142': {
    solpedNumber: '1420',
    solped: {
      unit: 'Unidad Solicitante',
      description: 'Equipamiento audiovisual sala de consejo',
      justification: 'Renovación de proyección y audio para sesiones del concejo municipal.',
      date: '2026-07-18',
      purchaseModality: 'agile_purchase',
      showResolution: false,
      lineDescription: 'Proyector laser 4K + sistema audio',
      lineQty: '1',
      linePrice: '2450000',
      estimatedAmount: '2450000',
    },
    budgetVerification: {
      insufficient: true,
      available: '320.000',
      committed: '180.000',
      requestAmount: '2.450.000',
      projected: '-2.310.000',
    },
    modalidad: {
      unit: 'Unidad Solicitante',
      modalityLabel: 'Compra Ágil (provisional)',
      monto: '2450000',
      modality: 'agile_purchase',
      catalogCm: false,
      jefaturaApproval: true,
    },
    vinculacionMp: {
      modalityLabel: 'Compra Ágil',
      mpCode: '',
      mpCodeLabel: 'ID Cotización',
      deepLinkLabel: 'Gestionar cotización en MP',
      statusLine: 'Bloqueado: etapa 1 sin cerrar (pendiente financiamiento)',
    },
    recepcion: {
      ocHeader: '— Recepción conforme',
      ocInfo: 'Bloqueado: sin OC (etapa 1 pendiente de financiamiento)',
      receiver: '—',
      lineItem: 'Proyector laser 4K + sistema audio',
      ocQty: '1',
    },
    pago: {
      ocHeader: '— Cruce de 3 vías',
      ocAmount: '—',
      ocSyncDate: '—',
      recepcionInfo: 'Bloqueado: etapa 1 pendiente',
      invoiceAmount: '—',
    },
  },
};

export function getFormPreset(expedienteId) {
  return formPresets[expedienteId] || formPresets['ADQ-2026-00123'];
}
